import multiply from 'multiply';

console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
console.log(multiply(2, 5));
